"use client";
import Link from "next/link";
import { useState } from "react";
import { ChevronDown, MessageCircle, Phone, Wifi, CreditCard, Wrench, ArrowRight } from "lucide-react";
import { SiteShell } from "@/components/project/site-shell";
import { Reveal } from "@/components/project/reveal";
const topics=[[Wifi,"Minha internet caiu","Confira sua conexão e fale com o atendimento técnico."],[Wrench,"Internet lenta ou instável","Orientações para Wi-Fi, velocidade e instabilidade."],[CreditCard,"Financeiro e pagamentos","Faturas, vencimentos e orientações financeiras."]];
const faq=[["Como falar com o suporte?","Escolha o assunto acima e fale com nossa equipe pelo canal mais adequado."],["Como consultar minha cobertura?","Acesse Cobertura, informe seu CEP e complete o endereço para verificar a disponibilidade."],["Onde vejo meu plano?","Acesse a Central do Cliente para visualizar seu plano e atalhos de atendimento."]];
export default function SupportPage(){const[open,setOpen]=useState<number|null>(null);return <SiteShell><section className="pp-page-hero"><div className="pp-page-hero-inner"><span className="pp-eyebrow"><i/> CENTRAL DE ATENDIMENTO</span><h1>Precisa de ajuda?<br/><em>Estamos aqui.</em></h1><p>Encontre rapidamente o canal certo para resolver sua necessidade.</p></div></section><section className="pp-section"><div className="pp-container"><Reveal className="pp-section-head"><div><span className="pp-eyebrow"><i/> ATENDIMENTO</span><h2>Como podemos ajudar?</h2></div><p>Escolha uma opção e vá direto ao assunto.</p></Reveal><div className="pp-grid-3">{topics.map(([Icon,title,text])=>{const I=Icon as typeof Wifi;return <Reveal key={title as string}><Link href="https://wa.me/5511987654321" className="pp-card"><div className="pp-card-icon"><I size={22}/></div><h3>{title as string}</h3><p>{text as string}</p><span style={{display:"inline-flex",alignItems:"center",gap:7,color:"#ff7900",fontSize:12,fontWeight:800,marginTop:18}}>Falar com atendimento <ArrowRight size={15}/></span></Link></Reveal>})}</div></div></section><section className="pp-stat-band"><div className="pp-container pp-stats"><div className="pp-stat"><strong>24/7</strong><span>CANAIS DIGITAIS</span></div><div className="pp-stat"><strong>WhatsApp</strong><span>ATENDIMENTO</span></div><div className="pp-stat"><strong>Humano</strong><span>SUPORTE</span></div><div className="pp-stat"><strong>Rápido</strong><span>RESPOSTAS</span></div></div></section><section className="pp-section pp-section-muted"><div className="pp-container"><Reveal className="pp-section-head"><div><span className="pp-eyebrow"><i/> FAQ</span><h2>Dúvidas frequentes.</h2></div></Reveal><div style={{maxWidth:850}}>{faq.map(([q,a],i)=><div key={q} style={{background:"#fff",border:"1px solid #e5eaf0",borderRadius:14,marginBottom:10,overflow:"hidden"}}><button type="button" onClick={()=>setOpen(open===i?null:i)} style={{width:"100%",padding:"20px",border:0,background:"transparent",display:"flex",justifyContent:"space-between",fontWeight:800,cursor:"pointer",textAlign:"left"}}><span>{q}</span><ChevronDown size={18} style={{transform:open===i?"rotate(180deg)":"none",transition:".2s"}}/></button>{open===i&&<p style={{padding:"0 20px 20px",color:"#64748b",fontSize:14,lineHeight:1.7}}>{a}</p>}</div>)}</div><div className="pp-actions" style={{marginTop:35}}><a className="pp-btn pp-btn-primary" href="https://wa.me/5511987654321"><MessageCircle size={17}/> WhatsApp</a><a className="pp-btn" style={{border:"1px solid #dce3ea",color:"#081522"}} href="tel:+5511987654321"><Phone size={17}/> Ligar agora</a></div></div></section></SiteShell>}
