"use client";
import Link from "next/link";
import { useState } from "react";
import { ArrowRight, ChevronDown, CreditCard, Headphones, MessageCircle, Phone, ShieldCheck, Wifi, Wrench } from "lucide-react";
import { SiteShell } from "@/components/project/site-shell";
import { Reveal } from "@/components/project/reveal";

const topics = [[Wifi,"Minha internet caiu","Faça uma verificação rápida e fale com o atendimento técnico."],[Wrench,"Internet lenta ou instável","Orientações para Wi-Fi, velocidade e instabilidade."],[CreditCard,"Financeiro e pagamentos","Faturas, vencimentos e orientações financeiras."]] as const;
const faq = [["Como falar com o suporte?","Escolha o assunto acima e fale com nossa equipe pelo canal mais adequado."],["Como consultar minha cobertura?","Acesse Cobertura, informe seu CEP e complete o endereço para verificar a disponibilidade."],["Onde vejo meu plano?","Acesse a Central do Cliente para visualizar seu plano, contrato e atalhos de atendimento."],["Minha conexão está lenta. O que posso fazer?","Verifique se o problema acontece em todos os dispositivos, aproxime-se do roteador e, se persistir, abra um atendimento para análise da rede."]] as const;

export default function SupportPage(){
 const [open,setOpen]=useState<number|null>(null);
 return <SiteShell><section className="pp-page-hero"><div className="pp-page-hero-inner"><span className="pp-eyebrow"><i/> CENTRAL DE ATENDIMENTO</span><h1>Precisa de ajuda?<br/><em>Estamos aqui.</em></h1><p>Encontre rapidamente o caminho certo para resolver sua necessidade, sem complicação.</p><div className="pp-actions"><a className="pp-btn pp-btn-primary" href="https://wa.me/5511987654321"><MessageCircle size={17}/> Falar no WhatsApp</a><Link className="pp-btn pp-btn-ghost" href="/cliente">Acessar Central</Link></div></div></section>
 <section className="pp-section"><div className="pp-container"><Reveal className="pp-section-head"><div><span className="pp-eyebrow"><i/> ATENDIMENTO</span><h2>Resolva em poucos passos.</h2></div><p>Escolha o assunto e vá direto para o canal de atendimento.</p></Reveal><div className="pp-grid-3">{topics.map(([Icon,title,text])=><Reveal key={title}><a href="https://wa.me/5511987654321" className="pp-card pp-card-interactive"><div className="pp-card-icon"><Icon size={22}/></div><h3>{title}</h3><p>{text}</p><span className="pp-card-arrow"><ArrowRight size={15}/></span></a></Reveal>)}</div></div></section>
 <section className="pp-section pp-section-muted"><div className="pp-container"><Reveal className="pp-section-head"><div><span className="pp-eyebrow"><i/> AUTONOMIA</span><h2>Antes de chamar, confira.</h2></div><p>Alguns problemas podem ser identificados em segundos.</p></Reveal><div className="pp-grid-3"><article className="pp-card"><div className="pp-card-icon"><Wifi size={22}/></div><h3>Verifique os dispositivos</h3><p>Se apenas um dispositivo estiver com problema, a causa pode estar nele e não na conexão.</p></article><article className="pp-card"><div className="pp-card-icon"><ShieldCheck size={22}/></div><h3>Confira sua rede Wi-Fi</h3><p>Observe a distância do roteador e teste a conexão em outro ambiente ou dispositivo.</p></article><article className="pp-card"><div className="pp-card-icon"><Headphones size={22}/></div><h3>Não resolveu?</h3><p>Nossa equipe pode analisar sua situação e orientar o próximo passo.</p></article></div></div></section>
 <section className="pp-stat-band"><div className="pp-container pp-stats"><div className="pp-stat"><strong>24/7</strong><span>CANAIS DIGITAIS</span></div><div className="pp-stat"><strong>WhatsApp</strong><span>ATENDIMENTO</span></div><div className="pp-stat"><strong>Humano</strong><span>SUPORTE</span></div><div className="pp-stat"><strong>Rápido</strong><span>RESPOSTAS</span></div></div></section>
 <section className="pp-section"><div className="pp-container"><Reveal className="pp-section-head"><div><span className="pp-eyebrow"><i/> FAQ</span><h2>Dúvidas frequentes.</h2></div></Reveal><div className="pp-faq">{faq.map(([q,a],i)=><div className="pp-faq-item" key={q}><button type="button" onClick={()=>setOpen(open===i?null:i)} aria-expanded={open===i}><span>{q}</span><ChevronDown size={18}/></button>{open===i&&<div className="pp-faq-answer">{a}</div>}</div>)}</div><div className="pp-actions"><a className="pp-btn pp-btn-primary" href="https://wa.me/5511987654321"><MessageCircle size={17}/> WhatsApp</a><a className="pp-btn pp-btn-ghost pp-btn-light" href="tel:+5511987654321"><Phone size={17}/> Ligar agora</a></div></div></section></SiteShell>
}
