import Link from "next/link";
import { ArrowRight, Gamepad2, Headphones, MonitorPlay, Smartphone, Wifi, Zap } from "lucide-react";
import { Reveal } from "@/components/project/reveal";
import { SiteShell } from "@/components/project/site-shell";

const experiences = [
  [MonitorPlay, "Streaming sem travar", "Assista em alta qualidade enquanto a casa continua conectada."],
  [Gamepad2, "Gaming com baixa latência", "Mais estabilidade para partidas, downloads e atualizações sem transformar a rede em gargalo."],
  [Headphones, "Música e conteúdo", "Seu entretenimento acompanha você em todos os dispositivos."],
] as const;

export default function EntretenimentoPage() {
  return <SiteShell><section className="pp-page-hero"><div className="pp-page-hero-inner"><span className="pp-eyebrow"><i/> PARQUE NET ENTRETENIMENTO</span><h1>Sua internet. Seu conteúdo. <em>Seu momento.</em></h1><p>Uma conexão preparada para streaming, gaming, música e todos os momentos digitais da sua casa.</p><div className="pp-actions"><Link className="pp-btn pp-btn-primary" href="/planos">Conhecer planos <ArrowRight size={17}/></Link><Link className="pp-btn pp-btn-ghost" href="/cobertura">Verificar cobertura</Link></div></div></section>
    <section className="pp-section"><div className="pp-container"><Reveal className="pp-section-head"><div><span className="pp-eyebrow"><i/> EXPERIÊNCIA DIGITAL</span><h2>Uma rede. Vários momentos.<br/>Tudo funcionando junto.</h2></div><p>Vários dispositivos, diferentes rotinas e uma única conexão trabalhando por você.</p></Reveal><div className="pp-grid-3">{experiences.map(([Icon,title,text])=><Reveal key={title}><article className="pp-card pp-card-interactive"><div className="pp-card-icon"><Icon size={22}/></div><h3>{title}</h3><p>{text}</p><span className="pp-card-arrow"><ArrowRight size={15}/></span></article></Reveal>)}</div></div></section>
    <section className="pp-section pp-section-muted"><div className="pp-container"><div className="pp-feature-grid"><Reveal><div className="pp-feature-copy"><span className="pp-eyebrow"><i/> CASA CONECTADA</span><h2>Quando a casa fica mais conectada, a internet precisa acompanhar.</h2><p>Streaming na TV, partidas no console, chamadas no notebook e celulares conectados ao mesmo tempo. A experiência começa com uma rede preparada.</p><div className="pp-checks"><span><MonitorPlay size={16}/> Streaming</span><span><Gamepad2 size={16}/> Gaming</span><span><Smartphone size={16}/> Multi-dispositivo</span></div><Link href="/planos" className="pp-btn pp-btn-primary">Escolher meu plano <ArrowRight size={16}/></Link></div></Reveal><Reveal><div className="pp-network-panel entertainment-panel"><div className="pp-network-line line-a"/><div className="pp-network-line line-b"/><div className="pp-network-line line-c"/><div className="pp-network-node node-a"><Wifi size={19}/></div><div className="pp-network-node node-b"><Gamepad2 size={19}/></div><div className="pp-network-node node-c"><MonitorPlay size={19}/></div><div className="pp-network-core"><Zap size={21}/><span>PARQUE NET</span><strong>HOME NETWORK</strong><small>ONLINE</small></div></div></Reveal></div></div></section>
    <section className="pp-stat-band"><div className="pp-container pp-stats"><div className="pp-stat"><strong>1 Gbps</strong><span>ATÉ DE VELOCIDADE</span></div><div className="pp-stat"><strong>4K</strong><span>STREAMING</span></div><div className="pp-stat"><strong>Baixa</strong><span>LATÊNCIA</span></div><div className="pp-stat"><strong>Multi</strong><span>DISPOSITIVOS</span></div></div></section>
    <section className="pp-cta"><div className="pp-cta-inner"><div><span className="pp-eyebrow"><i/> PRONTO PARA O PLAY</span><h2>Seu próximo momento começa aqui.</h2><p>Encontre o plano que combina com a sua casa.</p></div><Link className="pp-btn pp-btn-primary" href="/planos">Ver planos <Smartphone size={17}/></Link></div></section></SiteShell>;
}
