import Link from "next/link";
import { ArrowRight, Gamepad2, Headphones, MonitorPlay, Smartphone } from "lucide-react";
import { Reveal } from "@/components/project/reveal";
import { SiteShell } from "@/components/project/site-shell";

export default function EntretenimentoPage() {
  const items = [[MonitorPlay, "Streaming sem travar", "Assista em alta qualidade enquanto a casa continua conectada."], [Gamepad2, "Gaming com baixa latência", "Mais estabilidade para partidas competitivas, downloads e atualizações."], [Headphones, "Música e conteúdo", "Seu entretenimento acompanha você em todos os dispositivos."]];
  return <SiteShell><section className="pp-page-hero"><div className="pp-page-hero-inner"><span className="pp-eyebrow"><i /> PARQUE NET ENTRETENIMENTO</span><h1>Sua internet. Seu conteúdo. <em>Seu momento.</em></h1><p>Uma conexão preparada para streaming, gaming, música e todos os momentos digitais da sua casa.</p><div className="pp-actions"><Link className="pp-btn pp-btn-primary" href="/planos">Conhecer planos <ArrowRight size={17}/></Link><Link className="pp-btn pp-btn-ghost" href="/cobertura">Verificar cobertura</Link></div></div></section><section className="pp-section"><div className="pp-container"><Reveal className="pp-section-head"><div><span className="pp-eyebrow"><i /> EXPERIÊNCIA DIGITAL</span><h2>Faça mais com uma<br/>conexão que acompanha.</h2></div><p>Vários dispositivos, diferentes rotinas e uma única rede trabalhando por você.</p></Reveal><div className="pp-grid-3">{items.map(([Icon,title,text])=>{const I=Icon as typeof MonitorPlay;return <Reveal key={title as string}><article className="pp-card"><div className="pp-card-icon"><I size={22}/></div><h3>{title as string}</h3><p>{text as string}</p></article></Reveal>})}</div></div></section><section className="pp-stat-band"><div className="pp-container pp-stats"><div className="pp-stat"><strong>4 ms</strong><span>LATÊNCIA MÉDIA</span></div><div className="pp-stat"><strong>1 Gbps</strong><span>ATÉ DE VELOCIDADE</span></div><div className="pp-stat"><strong>4K</strong><span>STREAMING</span></div><div className="pp-stat"><strong>Multi</strong><span>DISPOSITIVOS</span></div></div></section><section className="pp-cta"><div className="pp-cta-inner"><div><span className="pp-eyebrow"><i /> PRONTO PARA O PLAY</span><h2>Seu próximo momento começa aqui.</h2><p>Encontre o plano que combina com a sua casa.</p></div><Link className="pp-btn pp-btn-primary" href="/planos">Ver planos <Smartphone size={17}/></Link></div></section></SiteShell>;
}
